use std::fs;
use std::process::Command;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let status = Command::new("curl")
        .args([
            "-L",
            "--fail",
            "https://raw.githubusercontent.com/vcrhonek/hwdata/refs/heads/master/pnp.ids",
            "-o",
            "pnp.ids",
        ])
        .status()?;

    if !status.success() {
        return Err("curl failed".into());
    }

    let input = fs::read_to_string("pnp.ids")?;

    let mut output = String::from(
        "// AUTO-GENERATED by `scripts/generate_pnp.rs` — DO NOT EDIT\n\
         // Source: https://github.com/vcrhonek/hwdata/blob/master/pnp.ids\n\
         // Regenerate with: cargo run --features scripts --bin update-pnp\n\n\
         const PNP_NAMES: &[(&str, &str)] = &[\n"
    );

    for line in input.lines() {
        let line = line.trim();

        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let Some((id, name)) = line.split_once(char::is_whitespace) else {
            continue;
        };

        let id = id.trim();
        let name = name.trim();

        output.push_str(&format!(
            "    ({:?}, {:?}),\n",
            id, name
        ));
    }

    output.push_str(
        r#"];

pub fn get_name(pnp_id: &str) -> Option<String> {
    PNP_NAMES
        .iter()
        .find(|(id, _)| *id == pnp_id)
        .map(|(_, name)| (*name).to_string())
}
"#,
    );

    fs::write("edid/src/pnp.rs", output)?;

    fs::remove_file("pnp.ids")?;

    Ok(())
}